### ISSUE TITLE
Übersetzung FAQ Argumente

### ISSUE THREAD

**Issue by ggbetz** [argumentation-online/argumentation.online#3]
@argumentation-online/ao-editors: Die Seite "Über Argumente"/"About Arguments" (`i18n/en/docusaurus-plugin-content-pages/about-arguments.md`) muss übersetzt werden.

**Comment by AndreasFrenzel** [comment]
Ich hatte den Edit-Button verwendet und dann committed. Als die Übersicht der Änderungen angezeigt wurde (mit rot und grün), habe ich vorsichtshalber alles in ein Textdokument gepasted, für den Fall, dass es nicht funktioniert hat. Hätte ich nach dem Committen noch etwas machen müssen, damit es tatsächlich als neue Version gespeichert wird?
(Ich habe bei meinen früheren Projekten auf Github immer mit der Commandline committed, wo man dann noch pushen musste.)

Ich werde es nun noch einmal versuchen. Vielleicht sehe ich im Editor ja, was falsch gelaufen ist.

**Comment by AndreasFrenzel** [comment]
Es sollte jetzt ein "Pull Request" geben. Vielleicht kann dadurch mein Commit zur aktuellen Version werden.

**Comment by ggbetz** [comment]
Danke @AndreasFrenzel !
