### ISSUE TITLE
Übersetzung der Unterseite "The project"

### ISSUE THREAD

**Issue by ggbetz** [argumentation-online/argumentation.online#4]
@argumentation-online/ao-editors : Die Seite "The project" (`i18n/en/docusaurus-plugin-content-pages/the-project.md`) muss übersetzt werden.

**Comment by AndreasFrenzel** [comment]
Ich habe die Seite übersetzt und ein Pull Request erstellt.

**Comment by ggbetz** [comment]
Danke!
