### ISSUE TITLE
Ort für Vorlagen-Dateien?

### ISSUE THREAD

**Issue by ggbetz** [argumentation-online/argumentation.online#6]
Hi @christianvoigt , wo wäre denn Deiner Meinung nach ein geeigneter Ort (in der Ordnerstruktur), um unsere Vorlagen-Dateien (md, docx/rtf) und zukünftig ggf. weitere Dateien abzulegen? Vielleicht ein neuer Ordner `/static/resources` -- analog zu `static/img`?

**Comment by christianvoigt** [comment]
ja genau. Alternativen:`static/downloads`,`static/files`

**Comment by ggbetz** [comment]
Danke!
